// Local PostgreSQL verification: uses the isolated existing SQL-check dependency.
import { PGlite } from '../../.cache/sql-check/node_modules/@electric-sql/pglite/dist/index.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create schema private;
create function auth.uid() returns uuid language sql as $$select current_setting('request.jwt.claim.sub',true)::uuid$$;
create table public.profiles(id uuid primary key,role text,is_active boolean);
create function private.is_aal2() returns boolean language sql as $$select current_setting('request.aal',true)='aal2'$$;
create function private.is_admin() returns boolean language sql security definer as $$select coalesce(private.is_aal2() and exists(select 1 from public.profiles where id=auth.uid() and role='admin' and is_active),false)$$;
grant usage on schema auth,private to authenticated;
insert into profiles values ('61000000-0000-0000-0000-000000000001','admin',true),('61000000-0000-0000-0000-000000000002','user',true),('61000000-0000-0000-0000-000000000003','user',true);
set request.jwt.claim.sub='61000000-0000-0000-0000-000000000001'; set request.aal='aal2';`);
for(const f of ['20260914000100_add_companies_and_sites.sql','20260914000200_enterprise_access_policy.sql','20260914000300_enterprise_access_activation.sql']) await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'));
const company='62000000-0000-0000-0000-000000000001',other='62000000-0000-0000-0000-000000000002',actor='61000000-0000-0000-0000-000000000002',site='63000000-0000-0000-0000-000000000001';
await db.query('insert into companies(id,code,name) values($1,\'C1\',\'Company\'),($2,\'C2\',\'Other\')',[company,other]);
await db.query('insert into sites(id,company_id,code,name) values($1,$2,\'S1\',\'Site\')',[site,company]);
const policy={levels:Array.from({length:5},(_,i)=>({id:i+1,name:`Level ${i+1}`,permissions:i===0?['menu','read','update','create'].map(action=>({resource:'settings.company',action,scope:'company'})):[]})),members:[{id:actor,name:'User',grade:'G',position:'P',level:1,organizationId:null,siteId:site,active:true,from:null,to:null}],mappings:[],roles:[],overrides:[]};
let checks=0;
const eq=(a,b)=>{assert.deepEqual(a,b);checks++};
const rejects=async(fn,code)=>{await assert.rejects(fn,e=>e.code===code);checks++};
const rpc=async(name,args=[],params='')=>(await db.query(`select public.${name}(${params}) result`,args)).rows[0].result;
const context=(id=company)=>rpc('enterprise_access_context',[id],'$1');
const save=(p,r)=>db.query('select * from enterprise_save_access_policy($1,$2,$3,\'test\')',[company,JSON.stringify(p),r]);
const publish=(d,r)=>rpc('enterprise_publish_access_policy',[company,d,r],'$1,$2,$3,\'publish\'');
const login=async(id)=>db.exec(`reset role;set request.jwt.claim.sub='${id}';set role authenticated`);
const admin=()=>login('61000000-0000-0000-0000-000000000001');
await admin();eq((await context()).mode,'legacy');await save(policy,0);eq((await publish(1,0)).revision,1);
await rejects(()=>publish(1,0),'40001');await rejects(()=>rpc('enterprise_revert_access_policy',[company,1],'$1,$2,\'revert\''),'22023');
await login(actor);eq((await context()).menuKeys,['settings.company']);eq((await db.query('select * from companies')).rows.length,1);
eq((await context(other)).mode,'active');eq((await context(other)).companyId,null);
await db.query('update sites set name=\'Edited\' where id=$1',[site]);
await rejects(()=>rpc('enterprise_access_companies'),'42501');
await login('61000000-0000-0000-0000-000000000003');eq((await context()).companies,[]);eq((await context()).mode,'active');
await admin();eq((await db.query('select * from companies')).rows.length,1);eq((await rpc('enterprise_access_companies')).length,2);
const denied=structuredClone(policy);denied.overrides=[{actorId:actor,resource:'settings.company',action:'read',scope:'company',effect:'deny',from:null,to:null}];
await save(denied,1);await login(actor);eq((await context()).menuKeys,['settings.company']);
await admin();await publish(2,1);await login(actor);eq((await context()).menuKeys,[]);eq((await db.query('select * from companies')).rows.length,0);
await admin();eq((await rpc('enterprise_revert_access_policy',[company,2],'$1,$2,\'restore\'')).revision,3);await login(actor);eq((await context()).menuKeys,['settings.company']);
await db.exec("reset role;update profiles set is_active=false where role='user';set role authenticated");await rejects(()=>context(),'42501');
await admin();await rejects(()=>db.query('update enterprise_access_publications set revision=90'),'42501');await db.exec("set request.aal='aal1'");await rejects(()=>publish(2,3),'42501');
await db.exec("reset role;update profiles set is_active=true;set request.aal='aal2'");await admin();
const scoped=structuredClone(policy);scoped.members[0].level=null;scoped.mappings=[{kind:'grade',code:'G',level:2,from:null,to:null},{kind:'position',code:'P',level:1,from:null,to:null}];scoped.levels[0].permissions.forEach(p=>p.scope='site');
await save(scoped,2);await publish(3,3);await login(actor);
eq((await context()).menuKeys,['settings.company']);eq((await context()).companyActions,[]);eq((await context()).siteActions,[{id:site,actions:['read','update']}]);eq((await db.query('select * from companies')).rows.length,0);eq((await db.query('select * from sites')).rows.length,1);
await rejects(()=>db.query("insert into sites(company_id,code,name) values($1,'NEW','Forbidden')",[company]),'42501');
await admin();const explicit=structuredClone(scoped);explicit.members[0].level=2;await save(explicit,3);await publish(4,4);await login(actor);eq((await context()).menuKeys,[]);
await admin();const role=structuredClone(explicit);role.roles=[{id:'reader',name:'Reader',members:[actor],permissions:[{resource:'dashboard',action:'menu',scope:'self'},{resource:'dashboard',action:'read',scope:'self'}]}];await save(role,4);await publish(5,5);await login(actor);eq((await context()).menuKeys,['dashboard']);
await rejects(()=>rpc('enterprise_access_sites',[company],'$1'),'42501');await admin();eq((await rpc('enterprise_access_sites',[company],'$1'))[0],{id:site,name:'Edited',companyId:company});await admin();const expired=structuredClone(role);expired.members[0].to='2000-01-01';await save(expired,5);await rejects(()=>publish(6,6),'22023');
// An inactive company retains explicit settings read/update for recovery, while business grants close.
const recovery=structuredClone(policy);recovery.levels[0].permissions.push({resource:'dashboard',action:'menu',scope:'company'},{resource:'dashboard',action:'read',scope:'company'});
await save(recovery,6);await publish(7,6);await login(actor);
await db.query('update companies set is_active=false where id=$1',[company]);
eq((await context()).menuKeys,['settings.company']);eq((await context()).companyActions,['read','update']);eq((await context()).companies.length,1);
eq((await db.query('select is_active from sites where id=$1',[site])).rows[0].is_active,false);
await admin();eq((await rpc('enterprise_access_companies')).length,2);await save(recovery,7);await publish(8,7);
await login(actor);await db.query('update companies set is_active=true where id=$1',[company]);eq((await context()).menuKeys,['dashboard','settings.company']);
// An organization-tree deny covers the actor's own organization navigation grant.
await admin();const tree=structuredClone(recovery);tree.members[0].organizationId='ORG';tree.levels[0].permissions=[{resource:'dashboard',action:'menu',scope:'organization'},{resource:'dashboard',action:'read',scope:'organization'}];tree.overrides=[{actorId:actor,resource:'dashboard',action:'read',scope:'organization_tree',effect:'deny',from:null,to:null}];await save(tree,8);await publish(9,8);await login(actor);eq((await context()).menuKeys,[]);
// Dated allow overrides alone are sufficient publication eligibility and runtime grants.
await admin();const overrideOnly=structuredClone(tree);overrideOnly.members[0].level=null;overrideOnly.overrides=['menu','read'].map(action=>({actorId:actor,resource:'dashboard',action,scope:'self',effect:'allow',from:null,to:null}));await save(overrideOnly,9);await publish(10,9);await login(actor);eq((await context()).menuKeys,['dashboard']);
console.log(`Activation migration: ${checks} PostgreSQL runtime assertions passed (auth helpers stubbed).`);await db.close();
