import { PGlite } from '../../.cache/sql-check/node_modules/@electric-sql/pglite/dist/index.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
let checks = 0;
const eq = (actual, expected) => { assert.deepEqual(actual, expected); checks++; };
const fails = async (fn, code = '42501', message) => { await assert.rejects(fn, e => e.code === code && (!message || e.message === message)); checks++; };
const admin = '61000000-0000-0000-0000-000000000001', actor = '61000000-0000-0000-0000-000000000002';
const company = '62000000-0000-0000-0000-000000000001', other = '62000000-0000-0000-0000-000000000002';
await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth;
create function auth.uid() returns uuid language sql as $$select current_setting('request.jwt.claim.sub',true)::uuid$$;
create function auth.jwt() returns jsonb language sql as $$select jsonb_build_object('aal',current_setting('request.aal',true))$$;
create table auth.users(id uuid primary key,email text,raw_app_meta_data jsonb);
grant usage on schema auth to authenticated;
set request.jwt.claim.sub='${admin}'; set request.aal='aal2';`);
// Run every real prior migration, including profiles, MFA, and provisioning;
// only the Supabase-owned auth surface is supplied by the local harness.
for (const file of fs.readdirSync('supabase/migrations').filter(f => /^\d.*\.sql$/.test(f) && f < '20260914000600').sort()) await db.exec(fs.readFileSync('supabase/migrations/' + file, 'utf8'));
await db.query("insert into auth.users values($1,'admin@gmail.com','{\"nexerp_provisioned\":true}'),($2,'actor@gmail.com','{\"nexerp_provisioned\":true}')", [admin, actor]);
await db.query("update profiles set role='admin' where id=$1", [admin]);
await db.query("insert into companies(id,code,name) values($1,'C1','Company'),($2,'O1','Other')", [company, other]);
const policy = { levels: Array.from({ length: 5 }, (_, i) => ({ id: i + 1, name: `L${i + 1}`, permissions: i === 0 ? ['hr.core', 'dashboard'].flatMap(resource => ['menu', 'read', 'create', 'update'].map(action => ({ resource, action, scope: 'company' }))) : [] })), members: [{ id: actor, name: 'HR', grade: '', position: '', level: 1, organizationId: null, siteId: null, active: true, from: null, to: null }], mappings: [], roles: [], overrides: [] };
const rpc = async (name, args = []) => (await db.query(`select public.${name}(${args.map((_, i) => '$' + (i + 1)).join(',')}) result`, args)).rows[0].result;
await rpc('enterprise_save_access_policy', [company, JSON.stringify(policy), 0, 'setup']);
await rpc('enterprise_publish_access_policy', [company, 1, 0, 'setup']);
const login = async (id = actor) => db.exec(`reset role;set request.jwt.claim.sub='${id}';set role authenticated`);
await login();
const employee = { employeeNo: 'E1', name: 'Employee', profileId: actor, hireDate: '2020-01-01', siteId: null, department: '', grade: '', position: '' };
const id = await rpc('hr_create_employee', [company, JSON.stringify(employee), 'existing data']);
const tomorrow = (await db.query("select ((now() at time zone 'Asia/Seoul')::date+1)::text d")).rows[0].d;
const action = await rpc('hr_record_personnel_action', [company, id, 1, JSON.stringify({ type: 'transfer', effectiveDate: tomorrow, siteId: null, department: '', grade: '', position: '', reason: 'existing future action' })]);
await db.exec('reset role');
const migration = 'supabase/migrations/20260914000600_hr_module_settings.sql';
if (fs.existsSync(migration)) await db.exec(fs.readFileSync(migration, 'utf8'));
await login(admin);
const settings = (c = company) => rpc('hr_module_settings', [c]);
const save = (state, rev = 0, visible = true, key = 'hr.core', reason = 'module change') => rpc('hr_save_module_settings', [company, key, rev, state, visible, reason]);
let result = await settings();
eq(result.companyId, company); eq(result.modules.length, 19);
eq(result.modules[0], { key: 'hr.core', label: '인사 기본', available: true, state: 'enabled', menuVisible: true, revision: 0, pendingActions: 1, dependents: [] });
eq(result.modules.slice(1).every(m => !m.available && m.state === 'disabled' && !m.menuVisible && m.revision === 0 && m.pendingActions === 0), true);
await fails(() => rpc('hr_directory', [company]));
await fails(() => save('enabled', 0, true, 'hr.payroll'), '22023', 'module_unavailable');
await fails(() => save('enabled', 0, true, 'hr.core', ' '), '22023');
await fails(() => save('invalid'), '22023'); await fails(() => save('enabled', 0, null), '22023');
await fails(() => save('read_only'), '22023', 'module_pending_actions');
await fails(() => save('disabled'), '22023', 'module_pending_actions');
result = await save('draining'); eq(result.modules[0].revision, 1);
await fails(() => save('enabled'), '40001', 'revision_conflict');
await login();
await fails(settings); await fails(() => save('enabled', 1));
const directory = () => rpc('hr_directory', [company]);
eq((await directory()).moduleState, 'draining'); eq((await directory()).permissions, { create: false, update: false, cancel: true });
await fails(() => rpc('hr_create_employee', [company, JSON.stringify({ ...employee, employeeNo: 'E2', profileId: null }), 'create']));
await fails(() => rpc('hr_correct_employee', [company, id, 2, JSON.stringify({ name: 'Changed', hireDate: '2020-01-01' }), 'correct']));
await fails(() => rpc('hr_record_personnel_action', [company, id, 2, '{}']));
await fails(() => rpc('hr_save_reference', [company, '{}', 0, 'reference']));
eq((await rpc('hr_reference_catalog', [company])).canManage, false);
// Draining cancellation retains the original update grant and never becomes a
// new standalone permission that widens access for read-only staff.
await db.exec('reset role');
const readOnly = structuredClone(policy);
readOnly.levels[0].permissions = readOnly.levels[0].permissions.filter(p => p.resource !== 'hr.core' || p.action !== 'update');
await db.query('update enterprise_access_publications set policy=$2 where company_id=$1', [company, JSON.stringify(readOnly)]);
await login(); eq((await directory()).permissions.cancel, false);
await fails(() => rpc('hr_cancel_personnel_action', [company, id, action, 2, 'no update grant']));
await db.exec('reset role');
await db.query('update enterprise_access_publications set policy=$2 where company_id=$1', [company, JSON.stringify(policy)]);
await login();
await rpc('hr_cancel_personnel_action', [company, id, action, 2, 'cancel pending']);
eq((await directory()).employees[0].revision, 3);
await login(admin); eq((await settings()).modules[0].pendingActions, 0);
await save('read_only', 1);
await login(); eq((await directory()).permissions, { create: false, update: false, cancel: false });
await fails(() => rpc('hr_cancel_personnel_action', [company, id, action, 3, 'deny']));
await login(admin); await save('enabled', 2, false);
await login();
let context = await rpc('enterprise_access_context', [company]);
eq(context.menuKeys.includes('hr.core'), true); eq(context.hiddenMenuKeys, ['hr.core']);
eq((await directory()).permissions, { create: true, update: true, cancel: true });
await login(admin); await save('disabled', 3);
await login(); context = await rpc('enterprise_access_context', [company]);
eq(context.menuKeys.includes('hr.core'), false); eq(context.menuKeys.includes('dashboard'), true); eq(context.hiddenMenuKeys, []);
await fails(directory); await fails(() => rpc('hr_reference_catalog', [company])); await fails(() => rpc('hr_employee_corrections', [company, id]));
await fails(() => rpc('hr_create_employee', [company, JSON.stringify({ ...employee, employeeNo: 'E2', profileId: null }), 'disabled']));
await fails(() => rpc('hr_correct_employee', [company, id, 3, JSON.stringify({ name: 'Changed', hireDate: '2020-01-01' }), 'disabled']));
await fails(() => rpc('hr_record_personnel_action', [company, id, 3, '{}']));
await fails(() => rpc('hr_cancel_personnel_action', [company, id, action, 3, 'disabled']));
await fails(() => rpc('hr_save_reference', [company, '{}', 0, 'disabled']));
await fails(() => rpc('hr_directory', [other]));
await fails(() => db.query('select * from hr_module_settings')); await fails(() => db.query('update hr_module_settings set state=\'enabled\''));
await login(admin); eq((await settings()).modules[0].state, 'disabled'); eq((await settings(other)).modules[0].state, 'enabled');
await db.exec("set request.aal='aal1'"); await fails(settings); await fails(() => save('enabled', 4));
await db.exec("set request.aal='aal2';reset role");
eq((await db.query('select count(*)::int n from hr_module_settings_audit')).rows[0].n, 4);
eq((await db.query('select count(*)::int n from hr_employees')).rows[0].n, 1);
// Mutations acquire the company lock during authorization, ahead of existing
// employee locks; volatile read entrypoints get fresh snapshots after waiting.
const definitions = (await db.query("select proname,provolatile,prosrc from pg_proc where pronamespace='public'::regnamespace and proname in ('hr_directory','hr_reference_catalog','hr_employee_corrections','hr_create_employee','hr_correct_employee','hr_record_personnel_action','hr_cancel_personnel_action','hr_save_reference')")).rows;
eq(definitions.every(f => f.provolatile === 'v'), true);
eq(definitions.filter(f => f.prosrc.includes('for update')).every(f => f.prosrc.indexOf('private.hr_authorize') < f.prosrc.indexOf('for update')), true);
const audit = (await db.query('select * from hr_module_settings_audit order by created_at,id')).rows;
eq(audit.every(row => row.created_by === admin && row.reason === 'module change' && row.module_key === 'hr.core'), true);
eq(audit.find(row => row.after_document.revision === 1).before_document.revision, 0);
eq(audit.find(row => row.after_document.revision === 4).before_document.state, 'enabled');
// Employment remains authoritative even while HR is closed: a due termination
// removes ERP access; reopening HR must not revive a terminated membership.
await db.query("insert into hr_personnel_actions(company_id,employee_id,type,effective_date,department,grade,position,created_by,reason) values($1,$2,'terminate',(now() at time zone 'Asia/Seoul')::date,'','','',$3,'termination')", [company, id, actor]);
await login(); eq((await rpc('enterprise_access_context', [company])).menuKeys, []);
await login(admin); await save('enabled', 4);
await login(); eq((await rpc('enterprise_access_context', [company])).menuKeys, []); await fails(directory);
await login(admin);
await fails(() => db.query('insert into hr_module_settings_audit default values'));
await fails(() => db.query("select private.enterprise_granted($1,'hr.core','read','company')", [company]));
console.log(`HR modules: ${checks} PostgreSQL runtime assertions passed.`);
await db.close();
